services:

  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    volumes:
      - ./etc/prometheus/:/etc/prometheus/
      - prom_data:/prometheus

  app:
    build: ./app
    deploy: 
      replicas: 3

volumes:
  prom_data: