global:
  scrape_interval: 5s # default 1m
  scrape_timeout: 5s # default 10s
  evaluation_interval: 5s # default 1m

rule_files:
  - "rules/instances_down_v1.yml"
  - "rules/instances_down_v2.yml"
  - "rules/instances_down_v3.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: app
    dns_sd_configs:
      - names: ["app"]
        type: "A"
        port: 2223
