# This is the rules file.

groups:
  - name: example
    rules:
      - alert: InstancesDown
        expr: sum(up{job="app"} OR on() vector(0)) == 0
        for: 1m
        labels:
          severity: page
        annotations:
          summary: "All instances of the App are down"
          description: "All instances of the App have been down for more than 1 minute(s)."
