# This is the main input for unit testing.
# Only this file is passed as command line argument.

rule_files:
  - instances_down_v3.yml

evaluation_interval: 1m

tests:

  - interval: 1m
    # Series data.
    input_series:
      - series: 'up{job="app", instance="app-1:2223"}'
        # _ _ _ _ _ _ _ _ _ _ _ _ _ _
        values: "_x14"
      - series: 'up{job="app", instance="app-2:2223"}'
        # 1 1 1 1 1 _ _ _ _ _ _ _ _ _ _ 1 1 1 1 1
        values: "1+0x4 _x9 1+0x4"

    alert_rule_test:

      - eval_time: 4m
        alertname: InstancesDownV3

      - eval_time: 11m
        alertname: InstancesDownV3
        exp_alerts:
          - exp_labels:
              severity: page
            exp_annotations:
              summary: "All instances of the App are down"
              description: "All instances of the App have been down for more than 1 minute(s)."

      - eval_time: 15m
        alertname: InstancesDownV3
