groups:
  - name: InstancesDownV1
    rules:
      - alert: InstancesDownV1
        expr: sum(up{job="app"}) == 0
        labels:
          severity: page
        annotations:
          summary: "All instances of the App are down"
          description: "All instances of the App have been down for more than 1 minute(s)."
