groups:
  - name: InstancesDownV2
    rules:
      - alert: InstancesDownV2
        expr: sum(up{job="app"} OR on() vector(0)) == 0
        labels:
          severity: page
        annotations:
          summary: "All instances of the App are down"
          description: "All instances of the App are down"
