# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run Prometheus
        run: docker compose up -d prometheus

      - name: Run Sample App
        run: docker compose up -d app

      - name: Run Test for Rules
        run: docker compose exec prometheus promtool test rules /etc/prometheus/rules/test.yml
