# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run App
        run: make start

      - name: Run Test for Rules
        run: make test
